import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
    index("routes/home.tsx"),
    route("about", "routes/about.tsx"),
    route("search", "routes/search.tsx"),
    route("collections", "routes/collections.tsx"),
    route("collections/:slug", "routes/collections.$slug.tsx"),
    route("products/:slug", "routes/products.$slug.tsx"),
    route("checkout", "routes/checkout.tsx"),
    route("checkout/success", "routes/checkout.success.tsx"),
    route("checkout/failed", "routes/checkout.failed.tsx"),
    route("order-confirmation", "routes/order-confirmation.tsx"),
    route("register", "routes/register.tsx"),
    route("forgot-password", "routes/forgot-password.tsx"),
    route("reset-password", "routes/reset-password.tsx"),
    route("verify-email", "routes/verify-email.tsx"),
    route("account", "routes/account.profile.tsx"),
    route("account/orders", "routes/account.orders.tsx"),
    route("account/orders/:id", "routes/account.orders.$id.tsx"),
    route("account/social", "routes/account.social.tsx"),
    route("account/reset-password", "routes/account.reset-password.tsx"),
    route("api/search", "routes/api.search.ts"),
    route("api/cart", "routes/api.cart.ts"),
    route("api/checkout", "routes/api.checkout.ts"),
    route("api/auth", "routes/api.auth.ts"),
    route("api/account", "routes/api.account.ts"),
] satisfies RouteConfig; 