// Generated from the Qatar zone/area reference list (English + Arabic neighborhood names
// per official Qatar addressing zone number). Kept in sync with the backend's copy at
// nutrient/src/plugins/qatar-shipping/data/qatar-areas.data.ts -- regenerate both together
// if the source list changes. zoneNumber 0 means the area has no official zone number
// assigned -- still a valid, priceable delivery area, since eligibility/pricing is keyed
// on the backend's area id, not the zone number.
import { qatarZones } from "./qatar";

export interface QatarArea {
  zoneNumber: number;
  nameEn: string;
  nameAr: string;
}

// The municipality (city) a zone number belongs to -- still needed to fill the address's
// `city` field even though the customer no longer picks it explicitly; derived from the
// same zoneCodes groupings in qatar.ts. Falls back to a generic "Qatar" for zoneNumber 0 --
// several of those areas share a name with a properly-zoned area elsewhere in the dataset
// (Al Waab, Al Themaid, Al Daayen, Al Ghaf...), so they're likely source-data duplicates
// rather than a genuinely distinct region, and there's no reliable way to auto-assign a
// specific municipality. city is display-only (not used for pricing/eligibility), so a
// generic value beats a blank one.
export function municipalityForZone(zoneNumber: number, locale: "en" | "ar" = "en"): string {
  const match = qatarZones.find((z) => z.zoneCodes.includes(zoneNumber));
  if (match) return match.municipality;
  return locale === "ar" ? "قطر" : "Qatar";
}

// Best-effort label for a zone number when the specific area the customer originally
// picked isn't known (e.g. rendering a previously-saved address) -- falls back to the
// first area on file for that zone, or "Zone N" if none exists in the reference list.
export function areaLabelForZone(zoneNumber: number, locale: "en" | "ar"): string {
  const area = qatarAreas.find((a) => a.zoneNumber === zoneNumber);
  if (area) return locale === "ar" ? area.nameAr : area.nameEn;
  return locale === "ar" ? `المنطقة ${zoneNumber}` : `Zone ${zoneNumber}`;
}

export const qatarAreas: QatarArea[] = [
  { zoneNumber: 0, nameEn: 'Aba Al Duloof', nameAr: 'ابا الظلوف' },
  { zoneNumber: 0, nameEn: 'Abal Hawaya', nameAr: 'ابا الحوايا' },
  { zoneNumber: 0, nameEn: 'Ain Mohammed', nameAr: 'عين محمد' },
  { zoneNumber: 0, nameEn: 'Ain Saleh', nameAr: 'عين صالح' },
  { zoneNumber: 0, nameEn: 'Al Daayen', nameAr: 'الظعاين' },
  { zoneNumber: 0, nameEn: 'Al Ghaf', nameAr: 'الغاف' },
  { zoneNumber: 0, nameEn: 'Al Ghafa', nameAr: 'الغافة' },
  { zoneNumber: 0, nameEn: 'Al Ghariya', nameAr: 'الغارية' },
  { zoneNumber: 0, nameEn: 'Al Gheena', nameAr: 'الغينة' },
  { zoneNumber: 0, nameEn: 'Al Hamm', nameAr: 'الهام' },
  { zoneNumber: 0, nameEn: 'Al Mamlaha', nameAr: 'المملحة' },
  { zoneNumber: 0, nameEn: 'Al Nuaman', nameAr: 'النعمان' },
  { zoneNumber: 0, nameEn: 'Al Reedan', nameAr: 'الريضان' },
  { zoneNumber: 0, nameEn: 'Al Ruwais', nameAr: 'الرويس' },
  { zoneNumber: 0, nameEn: 'Al Shehaimiya', nameAr: 'الشحيمية' },
  { zoneNumber: 0, nameEn: 'Al Thaghab', nameAr: 'الثغب' },
  { zoneNumber: 0, nameEn: 'Al Themaid', nameAr: 'الثميد' },
  { zoneNumber: 0, nameEn: 'Al Tuwaim', nameAr: 'التويم' },
  { zoneNumber: 0, nameEn: 'Al Waab', nameAr: 'الوعب' },
  { zoneNumber: 0, nameEn: 'Athba', nameAr: 'عذبة' },
  { zoneNumber: 0, nameEn: 'Bu Anz', nameAr: 'بو عنز' },
  { zoneNumber: 0, nameEn: 'Bu Braika', nameAr: 'بو بريكة' },
  { zoneNumber: 0, nameEn: 'Jery Bu Jefeer', nameAr: 'جري بو جفير' },
  { zoneNumber: 0, nameEn: 'Jery Lehmaidat', nameAr: 'جري لحميدات' },
  { zoneNumber: 0, nameEn: 'Jery Masha', nameAr: 'جري مشعا' },
  { zoneNumber: 0, nameEn: 'Lafaweya', nameAr: 'لعفاوية' },
  { zoneNumber: 0, nameEn: 'Legaabiya', nameAr: 'لقعابية' },
  { zoneNumber: 0, nameEn: 'Lejthooiya', nameAr: 'لجذوعية' },
  { zoneNumber: 0, nameEn: 'Lemzarra', nameAr: 'لمزرع' },
  { zoneNumber: 0, nameEn: 'Lesha', nameAr: 'لشا' },
  { zoneNumber: 0, nameEn: 'Mekeen', nameAr: 'مكين' },
  { zoneNumber: 0, nameEn: 'Merweb', nameAr: 'مروب' },
  { zoneNumber: 0, nameEn: 'Mesaika', nameAr: 'مسيكة' },
  { zoneNumber: 0, nameEn: 'Rawdat Shraim', nameAr: 'روضة اشريم' },
  { zoneNumber: 0, nameEn: 'Sidriyat Al Hamm', nameAr: 'سدرية الهام' },
  { zoneNumber: 0, nameEn: 'Umm Al Hawaya', nameAr: 'ام الحوايا' },
  { zoneNumber: 0, nameEn: 'Umm Al Soof', nameAr: 'ام الصوف' },
  { zoneNumber: 0, nameEn: 'Umm Ghuwaifa', nameAr: 'ام اغويفة' },
  { zoneNumber: 0, nameEn: 'Umm Jasim', nameAr: 'ام جاسم' },
  { zoneNumber: 0, nameEn: 'Umm Lekhsaf', nameAr: 'ام لخصاف' },
  { zoneNumber: 0, nameEn: 'Umm Sabbah', nameAr: 'ام صباح' },
  { zoneNumber: 0, nameEn: 'Wadi Al Debaian', nameAr: 'وادي الضبيعان' },
  { zoneNumber: 0, nameEn: 'Wadi Al Ghesen', nameAr: 'وادي الغصن' },
  { zoneNumber: 0, nameEn: 'Wadi Al Jahiliya', nameAr: 'وادي الجاهلية' },
  { zoneNumber: 1, nameEn: 'Al Jasra', nameAr: 'الجسرة' },
  { zoneNumber: 2, nameEn: 'Al Bidda', nameAr: 'البدع' },
  { zoneNumber: 3, nameEn: 'Mushaireb', nameAr: 'مشيرب' },
  { zoneNumber: 4, nameEn: 'Mushaireb', nameAr: 'مشيرب' },
  { zoneNumber: 5, nameEn: 'Al Najada', nameAr: 'النجادة' },
  { zoneNumber: 5, nameEn: 'Barahat Al Jufairi', nameAr: 'براحة الجفيري' },
  { zoneNumber: 5, nameEn: 'Fereej Al Asmakh', nameAr: 'فريج الاصمخ' },
  { zoneNumber: 6, nameEn: 'Old Al Ghanim', nameAr: 'الغانم العتيق' },
  { zoneNumber: 7, nameEn: 'Al Souq', nameAr: 'السوق' },
  { zoneNumber: 12, nameEn: 'Al Bidda', nameAr: 'البدع' },
  { zoneNumber: 12, nameEn: 'Rumaila', nameAr: 'رميلة' },
  { zoneNumber: 12, nameEn: 'Wadi Al Sail', nameAr: 'وادي السيل' },
  { zoneNumber: 13, nameEn: 'Mushaireb', nameAr: 'مشيرب' },
  { zoneNumber: 14, nameEn: 'Fereej Abdel Aziz', nameAr: 'فريج عبد العزيز' },
  { zoneNumber: 15, nameEn: 'Al Doha Al Jadeeda', nameAr: 'الدوحة الجديدة' },
  { zoneNumber: 16, nameEn: 'Old Al Ghanim', nameAr: 'الغانم العتيق' },
  { zoneNumber: 17, nameEn: 'Al Hitmi', nameAr: 'الهتمي' },
  { zoneNumber: 17, nameEn: 'Al Rufaa', nameAr: 'الرفاع' },
  { zoneNumber: 18, nameEn: 'Al Mirqab', nameAr: 'المرقاب' },
  { zoneNumber: 18, nameEn: 'Slata', nameAr: 'اسلطة' },
  { zoneNumber: 19, nameEn: 'Doha Port', nameAr: 'ميناء الدوحة' },
  { zoneNumber: 20, nameEn: 'Wadi Al Sail', nameAr: 'وادي السيل' },
  { zoneNumber: 21, nameEn: 'Rumaila', nameAr: 'رميلة' },
  { zoneNumber: 22, nameEn: 'Fereej Bin Mahmoud', nameAr: 'فريج بن محمود' },
  { zoneNumber: 23, nameEn: 'Fereej Bin Mahmoud', nameAr: 'فريج بن محمود' },
  { zoneNumber: 24, nameEn: 'Rawdat Al Khail', nameAr: 'روضة الخيل' },
  { zoneNumber: 25, nameEn: 'Al Mansoura', nameAr: 'المنصورة' },
  { zoneNumber: 25, nameEn: 'Fereej Bin Derhem', nameAr: 'فريج بن درهم' },
  { zoneNumber: 26, nameEn: 'Najma', nameAr: 'نجمة' },
  { zoneNumber: 27, nameEn: 'Umm Ghuwailina', nameAr: 'ام غويلينة' },
  { zoneNumber: 28, nameEn: 'Al Khulaifat', nameAr: 'الخليفات' },
  { zoneNumber: 28, nameEn: 'Ras Bu Abboud', nameAr: 'راس بو عبود' },
  { zoneNumber: 29, nameEn: 'Ras Bu Abboud', nameAr: 'راس بو عبود' },
  { zoneNumber: 30, nameEn: 'Duhail', nameAr: 'دحيل' },
  { zoneNumber: 31, nameEn: 'Umm Lekhba', nameAr: 'ام لخبا' },
  { zoneNumber: 32, nameEn: 'Dahl Al Hamam', nameAr: 'دحل الحمام' },
  { zoneNumber: 32, nameEn: 'Madinat Khalifa North', nameAr: 'مدينة خليفة الشمالية' },
  { zoneNumber: 33, nameEn: 'Al Markhiya', nameAr: 'المرخية' },
  { zoneNumber: 34, nameEn: 'Madinat Khalifa South', nameAr: 'مدينة خليفة الجنوبية' },
  { zoneNumber: 35, nameEn: 'Fereej Kulaib', nameAr: 'فريج كليب' },
  { zoneNumber: 36, nameEn: 'Al Messila', nameAr: 'المسيلة' },
  { zoneNumber: 37, nameEn: 'Fereej Bin Omran', nameAr: 'فريج بن عمران' },
  { zoneNumber: 37, nameEn: 'Hamad Medical City', nameAr: 'مدينة حمد الطبية' },
  { zoneNumber: 37, nameEn: 'New Al Hitmi', nameAr: 'الهتمي الجديد' },
  { zoneNumber: 38, nameEn: 'Al Sadd', nameAr: 'السد' },
  { zoneNumber: 39, nameEn: 'Al Mirqab Al Jadeed', nameAr: 'المرقاب الجديد' },
  { zoneNumber: 39, nameEn: 'Al Sadd', nameAr: 'السد' },
  { zoneNumber: 39, nameEn: 'Fereej Al Nasr', nameAr: 'فريج النصر' },
  { zoneNumber: 40, nameEn: 'New Slata', nameAr: 'اسلطة الجديدة' },
  { zoneNumber: 41, nameEn: 'Nuaija', nameAr: 'نعيجة' },
  { zoneNumber: 42, nameEn: 'Al Hilal', nameAr: 'الهلال' },
  { zoneNumber: 43, nameEn: 'Al Maamoura', nameAr: 'المعمورة' },
  { zoneNumber: 43, nameEn: 'Nuaija', nameAr: 'نعيجة' },
  { zoneNumber: 44, nameEn: 'Nuaija', nameAr: 'نعيجة' },
  { zoneNumber: 45, nameEn: 'Old Airport', nameAr: 'المطار العتيق' },
  { zoneNumber: 46, nameEn: 'Al Thumama', nameAr: 'الثمامة' },
  { zoneNumber: 47, nameEn: 'Al Thumama', nameAr: 'الثمامة' },
  { zoneNumber: 48, nameEn: 'Doha International Airport', nameAr: 'مطار الدوحة الدولي' },
  { zoneNumber: 49, nameEn: 'Banana Island', nameAr: 'جزيرة البنانا' },
  { zoneNumber: 49, nameEn: 'Hamad International Airport', nameAr: 'مطار حمد الدولي' },
  { zoneNumber: 49, nameEn: 'Ras Bu Funtas', nameAr: 'راس بو فنطاس' },
  { zoneNumber: 50, nameEn: 'Al Thumama', nameAr: 'الثمامة' },
  { zoneNumber: 51, nameEn: 'Al Gharrafa', nameAr: 'الغرافة' },
  { zoneNumber: 51, nameEn: 'Al Seej', nameAr: 'السيج' },
  { zoneNumber: 51, nameEn: 'Al Themaid', nameAr: 'الثميد' },
  { zoneNumber: 51, nameEn: 'Bani Hajer', nameAr: 'بني هاجر' },
  { zoneNumber: 51, nameEn: 'Fereej Al Attiya', nameAr: 'فريج العطية' },
  { zoneNumber: 51, nameEn: 'Fereej Al Zaeem', nameAr: 'فريج الزعيم' },
  { zoneNumber: 51, nameEn: 'Gharrafat Al Rayyan', nameAr: 'غرافة الريان' },
  { zoneNumber: 51, nameEn: 'Izghawa', nameAr: 'ازغوى' },
  { zoneNumber: 51, nameEn: 'Jery Al Dabi', nameAr: 'جري الظبي' },
  { zoneNumber: 51, nameEn: 'Jeryan Al Saham', nameAr: 'جريان السهم' },
  { zoneNumber: 51, nameEn: 'Rawdat Al Jahhaniya', nameAr: 'روضة الجهانية' },
  { zoneNumber: 51, nameEn: 'Rawdat Egdaim', nameAr: 'روضة اقديم' },
  { zoneNumber: 51, nameEn: 'Shariya', nameAr: 'شرية' },
  { zoneNumber: 51, nameEn: 'Umm Al Afaei', nameAr: 'ام الافاعي' },
  { zoneNumber: 52, nameEn: 'Al Luqta', nameAr: 'اللقطة' },
  { zoneNumber: 52, nameEn: 'Al Shagub', nameAr: 'الشقب' },
  { zoneNumber: 52, nameEn: 'Lebday', nameAr: 'لبديع' },
  { zoneNumber: 52, nameEn: 'Old Al Rayyan', nameAr: 'الريان العتيق' },
  { zoneNumber: 53, nameEn: 'Al Wajba', nameAr: 'الوجبة' },
  { zoneNumber: 53, nameEn: 'Magroon Al Markhiya', nameAr: 'مقرون المرخية' },
  { zoneNumber: 53, nameEn: 'Muaither', nameAr: 'معيذر' },
  { zoneNumber: 53, nameEn: 'New Al Rayyan', nameAr: 'الريان الجديد' },
  { zoneNumber: 53, nameEn: 'Rawdat Abal Heeran', nameAr: 'روضة ابا الحيران' },
  { zoneNumber: 53, nameEn: 'Rawdat Al Naisar', nameAr: 'روضة النيسر' },
  { zoneNumber: 53, nameEn: 'Umm Al Juwashen', nameAr: 'ام الجواشن' },
  { zoneNumber: 54, nameEn: 'Amuraikh Al Janoubi', nameAr: 'امريخ الجنوبي' },
  { zoneNumber: 54, nameEn: 'Baaya', nameAr: 'بعيا' },
  { zoneNumber: 54, nameEn: 'Fereej Al Amir', nameAr: 'فريج الأمير' },
  { zoneNumber: 54, nameEn: 'Fereej Al Soudan', nameAr: 'فريج السودان' },
  { zoneNumber: 54, nameEn: 'Luaib', nameAr: 'لوعيب' },
  { zoneNumber: 54, nameEn: 'Muraikh', nameAr: 'مريخ' },
  { zoneNumber: 55, nameEn: 'Al Aziziya', nameAr: 'العزيزية' },
  { zoneNumber: 55, nameEn: 'Al Ghanim Al Jadeed', nameAr: 'الغانم الجديد' },
  { zoneNumber: 55, nameEn: 'Al Mearad', nameAr: 'المعراض' },
  { zoneNumber: 55, nameEn: 'Al Sailiya', nameAr: 'السيلية' },
  { zoneNumber: 55, nameEn: 'Al Waab', nameAr: 'الوعب' },
  { zoneNumber: 55, nameEn: 'Bu Sidra', nameAr: 'بو سدرة' },
  { zoneNumber: 55, nameEn: 'Fereej Al Manaseer', nameAr: 'فريج المناصير' },
  { zoneNumber: 55, nameEn: 'Fereej Al Murra', nameAr: 'فريج المرة' },
  { zoneNumber: 55, nameEn: 'Fereej Al Soudan', nameAr: 'فريج السودان' },
  { zoneNumber: 55, nameEn: 'Muaither', nameAr: 'معيذر' },
  { zoneNumber: 56, nameEn: 'Ain Khaled', nameAr: 'عين خالد' },
  { zoneNumber: 56, nameEn: 'Al Maamoura', nameAr: 'المعمورة' },
  { zoneNumber: 56, nameEn: 'Bu Hamour', nameAr: 'بو هامور' },
  { zoneNumber: 56, nameEn: 'Mesaimeer', nameAr: 'مسيمير' },
  { zoneNumber: 56, nameEn: 'Umm Al Seneem', nameAr: 'ام السنيم' },
  { zoneNumber: 57, nameEn: 'Industrial Area', nameAr: 'المنطقة الصناعية' },
  { zoneNumber: 58, nameEn: 'Wholesale Market', nameAr: 'السوق المركزي' },
  { zoneNumber: 60, nameEn: 'Al Dafna', nameAr: 'الدفنة' },
  { zoneNumber: 61, nameEn: 'Al Dafna', nameAr: 'الدفنة' },
  { zoneNumber: 61, nameEn: 'Al Gassar', nameAr: 'القصار' },
  { zoneNumber: 62, nameEn: 'Lekhwair', nameAr: 'لخوير' },
  { zoneNumber: 63, nameEn: 'Onaiza', nameAr: 'عنيزة' },
  { zoneNumber: 64, nameEn: 'Lejbailat', nameAr: 'لجبيلات' },
  { zoneNumber: 65, nameEn: 'Onaiza', nameAr: 'عنيزة' },
  { zoneNumber: 66, nameEn: 'Al Gassar', nameAr: 'القصار' },
  { zoneNumber: 66, nameEn: 'Legtaifiya', nameAr: 'لقطيفية' },
  { zoneNumber: 66, nameEn: 'Onaiza', nameAr: 'عنيزة' },
  { zoneNumber: 66, nameEn: 'The Pearl Island', nameAr: 'جزيرة اللؤلؤة' },
  { zoneNumber: 67, nameEn: 'Hazm Al Markhiya', nameAr: 'حزم المرخية' },
  { zoneNumber: 68, nameEn: 'Al Tarfa', nameAr: 'الطرفة' },
  { zoneNumber: 68, nameEn: 'Jelaiah', nameAr: 'جليعة' },
  { zoneNumber: 68, nameEn: 'Jeryan Nejaima', nameAr: 'جريان نجيمة' },
  { zoneNumber: 69, nameEn: 'Al Egla', nameAr: 'العقلة' },
  { zoneNumber: 69, nameEn: 'Al Kharayej', nameAr: 'الخرايج' },
  { zoneNumber: 69, nameEn: 'Ghar Thuaileb', nameAr: 'غار ثعيلب' },
  { zoneNumber: 69, nameEn: 'Lusail', nameAr: 'لوسيل' },
  { zoneNumber: 70, nameEn: 'Al Daayen', nameAr: 'الظعاين' },
  { zoneNumber: 70, nameEn: 'Al Ebb', nameAr: 'العب' },
  { zoneNumber: 70, nameEn: 'Al Jeryan', nameAr: 'الجريان' },
  { zoneNumber: 70, nameEn: 'Al Kheesa', nameAr: 'الخيسة' },
  { zoneNumber: 70, nameEn: 'Al Masrouhiya', nameAr: 'المسروحية' },
  { zoneNumber: 70, nameEn: 'Al Rehayya', nameAr: 'الرحية' },
  { zoneNumber: 70, nameEn: 'Al Sakhama', nameAr: 'الصخامة' },
  { zoneNumber: 70, nameEn: 'Halat Awbair', nameAr: 'حالة اوبير' },
  { zoneNumber: 70, nameEn: 'Jery Al Matrooshi', nameAr: 'جري المطروشي' },
  { zoneNumber: 70, nameEn: 'Jeryan Jenaihat', nameAr: 'جريان جنيحات' },
  { zoneNumber: 70, nameEn: 'Leabaib', nameAr: 'لعبيب' },
  { zoneNumber: 70, nameEn: 'Lusail', nameAr: 'لوسيل' },
  { zoneNumber: 70, nameEn: 'Rawdat Al Hamama', nameAr: 'روضة الحمامة' },
  { zoneNumber: 70, nameEn: 'Semaisma', nameAr: 'سميسمة' },
  { zoneNumber: 70, nameEn: 'Tenbek', nameAr: 'تنبك' },
  { zoneNumber: 70, nameEn: 'Umm Garn', nameAr: 'ام قرن' },
  { zoneNumber: 70, nameEn: 'Wadi Al Banat', nameAr: 'وادي البنات' },
  { zoneNumber: 70, nameEn: 'Wadi Al Ewaira', nameAr: 'وادي العويرة' },
  { zoneNumber: 70, nameEn: 'Wadi Al Wasah', nameAr: 'وادي الوسعة' },
  { zoneNumber: 70, nameEn: 'Wadi Lusail', nameAr: 'وادي لوسيل' },
  { zoneNumber: 71, nameEn: 'Abal Heeran', nameAr: 'ابا الحيران' },
  { zoneNumber: 71, nameEn: 'Abal Najem', nameAr: 'ابا النجم' },
  { zoneNumber: 71, nameEn: 'Al Froosh', nameAr: 'الفروش' },
  { zoneNumber: 71, nameEn: 'Al Kharaitiyat', nameAr: 'الخريطيات' },
  { zoneNumber: 71, nameEn: 'Al Masluba', nameAr: 'المصلبه' },
  { zoneNumber: 71, nameEn: 'Al Mazrooah', nameAr: 'المزروعه' },
  { zoneNumber: 71, nameEn: 'Al Shefallahiya', nameAr: 'الشفلحيه' },
  { zoneNumber: 71, nameEn: 'Bu Fass', nameAr: 'بو فاس' },
  { zoneNumber: 71, nameEn: 'Bu Fesseela', nameAr: 'بو فسيلة' },
  { zoneNumber: 71, nameEn: 'Bu Garn', nameAr: 'بو قرن' },
  { zoneNumber: 71, nameEn: 'Bu Glaila', nameAr: 'بو اقليلة' },
  { zoneNumber: 71, nameEn: 'Bu Hesayya', nameAr: 'بو حصيه' },
  { zoneNumber: 71, nameEn: 'Bu Merzaz', nameAr: 'بو مرزاز' },
  { zoneNumber: 71, nameEn: 'Bu Thaila', nameAr: 'بو ثيله' },
  { zoneNumber: 71, nameEn: 'Izghawa', nameAr: 'ازغوى' },
  { zoneNumber: 71, nameEn: 'Jery Al Samur', nameAr: 'جري السمر' },
  { zoneNumber: 71, nameEn: 'Jery Khabbab', nameAr: 'جري خباب' },
  { zoneNumber: 71, nameEn: 'Muaither Al Dasem', nameAr: 'معيذر الدسم' },
  { zoneNumber: 71, nameEn: 'Muaither Al Meshaf', nameAr: 'معيذر المشاف' },
  { zoneNumber: 71, nameEn: 'Snay Lehmaidi', nameAr: 'صنيع لحميدي' },
  { zoneNumber: 71, nameEn: 'Umm Al Amad', nameAr: 'ام العمد' },
  { zoneNumber: 71, nameEn: 'Umm Ebairiya', nameAr: 'ام عبيرية' },
  { zoneNumber: 71, nameEn: 'Umm Shaharain', nameAr: 'ام اشهرين' },
  { zoneNumber: 71, nameEn: 'Umm Slal Ali', nameAr: 'ام صلال علي' },
  { zoneNumber: 71, nameEn: 'Umm Slal Mohammed', nameAr: 'ام صلال محمد' },
  { zoneNumber: 71, nameEn: 'Wadi Al Askar', nameAr: 'وادي العسكر' },
  { zoneNumber: 71, nameEn: 'Wadi Al Mazrooah', nameAr: 'وادي المزروعه' },
  { zoneNumber: 71, nameEn: 'Wadi Al Waab', nameAr: 'وادي الوعب' },
  { zoneNumber: 72, nameEn: 'Aba Erbayyat', nameAr: 'ابا اربيات' },
  { zoneNumber: 72, nameEn: 'Abal Awsaj', nameAr: 'ابا العوسج' },
  { zoneNumber: 72, nameEn: 'Abal Hasak', nameAr: 'ابا الحسك' },
  { zoneNumber: 72, nameEn: 'Al Dehailiyat', nameAr: 'الدحيليات' },
  { zoneNumber: 72, nameEn: 'Al Negaibat', nameAr: 'النقيبات' },
  { zoneNumber: 72, nameEn: 'Al Refaig', nameAr: 'الرفيق' },
  { zoneNumber: 72, nameEn: 'Al Sena', nameAr: 'الصنع' },
  { zoneNumber: 72, nameEn: 'Al Senaiat', nameAr: 'الصنيعات' },
  { zoneNumber: 72, nameEn: 'Atran', nameAr: 'عطران' },
  { zoneNumber: 72, nameEn: 'Broog', nameAr: 'بروق' },
  { zoneNumber: 72, nameEn: 'Bu Ghameela', nameAr: 'بو غميلة' },
  { zoneNumber: 72, nameEn: 'Bu Haweyya', nameAr: 'بو حوية' },
  { zoneNumber: 72, nameEn: 'Bu Kheesa', nameAr: 'بو خيسة' },
  { zoneNumber: 72, nameEn: 'Bu Thughaib', nameAr: 'بو ثغيب' },
  { zoneNumber: 72, nameEn: 'Ebsaiteen', nameAr: 'ابسيتين' },
  { zoneNumber: 72, nameEn: 'Grayyat Al Eid', nameAr: 'اقريات العيد' },
  { zoneNumber: 72, nameEn: 'Hafeerat Rawdan', nameAr: 'حفيرات روضان' },
  { zoneNumber: 72, nameEn: 'Heenat Al Silla', nameAr: 'حينة الصلة' },
  { zoneNumber: 72, nameEn: 'Imraibdat', nameAr: 'امريبضات' },
  { zoneNumber: 72, nameEn: 'Jery Al Dabi', nameAr: 'جري الظبي' },
  { zoneNumber: 72, nameEn: 'Jery Bu Esh', nameAr: 'جري بو عش' },
  { zoneNumber: 72, nameEn: 'Jery Rabdan', nameAr: 'جري ربدان' },
  { zoneNumber: 72, nameEn: 'Jery Tallaa', nameAr: 'جري طلاع' },
  { zoneNumber: 72, nameEn: 'Leagooriyat', nameAr: 'لعقوريات' },
  { zoneNumber: 72, nameEn: 'Leatooriya', nameAr: 'لعطورية' },
  { zoneNumber: 72, nameEn: 'Leawaijat', nameAr: 'لعويجات' },
  { zoneNumber: 72, nameEn: 'Lebraithat', nameAr: 'لبريثات' },
  { zoneNumber: 72, nameEn: 'Lehsain', nameAr: 'لحصين' },
  { zoneNumber: 72, nameEn: 'Ras Broog', nameAr: 'راس بروق' },
  { zoneNumber: 72, nameEn: 'Rawdat Al Ejla', nameAr: 'روضة العجلة' },
  { zoneNumber: 72, nameEn: 'Rawdat Al Faras', nameAr: 'روضة الفرس' },
  { zoneNumber: 72, nameEn: 'Rawdat Al Imnailat', nameAr: 'روضة المنيلات' },
  { zoneNumber: 72, nameEn: 'Rawdat Al Khanayen', nameAr: 'روضة الخناين' },
  { zoneNumber: 72, nameEn: 'Rawdat Al Mawda', nameAr: 'روضة الموضع' },
  { zoneNumber: 72, nameEn: 'Rawdat Khawzan', nameAr: 'روضة خوزان' },
  { zoneNumber: 72, nameEn: 'Slemiyet Bu Ejthaya', nameAr: 'اسلمية بو جذيع' },
  { zoneNumber: 72, nameEn: 'Umm Ethnaitain', nameAr: 'ام اثنيتين' },
  { zoneNumber: 72, nameEn: 'Umm Leadam', nameAr: 'ام لعظام' },
  { zoneNumber: 72, nameEn: 'Umm Leghab West', nameAr: 'ام لقهاب الغربية' },
  { zoneNumber: 72, nameEn: 'Umm Zraibeel', nameAr: 'ام ازريبيل' },
  { zoneNumber: 72, nameEn: 'Ummahat Al Hass', nameAr: 'امهات الحاس' },
  { zoneNumber: 72, nameEn: 'Waab Al Nasla', nameAr: 'وعب النصلة' },
  { zoneNumber: 72, nameEn: 'Waab Suwailem', nameAr: 'وعب سويلم' },
  { zoneNumber: 72, nameEn: 'Wadi Al Salam', nameAr: 'وادي السلم' },
  { zoneNumber: 72, nameEn: 'Wadi Bu Ejthaya', nameAr: 'وادي بو جذيع' },
  { zoneNumber: 72, nameEn: 'Wadi Khawzan', nameAr: 'وادي خوزان' },
  { zoneNumber: 72, nameEn: 'Wadi Laswag', nameAr: 'وادي لسواق' },
  { zoneNumber: 72, nameEn: 'Wadi Saleh', nameAr: 'وادي صالح' },
  { zoneNumber: 72, nameEn: 'Zekreet', nameAr: 'زكريت' },
  { zoneNumber: 73, nameEn: 'Aba Erbayyat', nameAr: 'ابا اربيات' },
  { zoneNumber: 73, nameEn: 'Aba Seneem', nameAr: 'ابا السنيم' },
  { zoneNumber: 73, nameEn: 'Abal Egdooh', nameAr: 'ابا القدوح' },
  { zoneNumber: 73, nameEn: 'Abal Jahazel', nameAr: 'ابا الجحازل' },
  { zoneNumber: 73, nameEn: 'Abal Mashmoom', nameAr: 'ابا المشموم' },
  { zoneNumber: 73, nameEn: 'Ain Umm Al Zebad', nameAr: 'عين ام الزبد' },
  { zoneNumber: 73, nameEn: 'Al Gaeyya', nameAr: 'القاعيه' },
  { zoneNumber: 73, nameEn: 'Al Ghadeeriyat', nameAr: 'الغديريات' },
  { zoneNumber: 73, nameEn: 'Al Haddaya', nameAr: 'الهداية' },
  { zoneNumber: 73, nameEn: 'Al Hasheemiya', nameAr: 'الهشيميه' },
  { zoneNumber: 73, nameEn: 'Al Hawafer', nameAr: 'الحوافر' },
  { zoneNumber: 73, nameEn: 'Al Magta', nameAr: 'المقطع' },
  { zoneNumber: 73, nameEn: 'Al Metbarga', nameAr: 'المتبارقه' },
  { zoneNumber: 73, nameEn: 'Al Nefayed', nameAr: 'النفايد' },
  { zoneNumber: 73, nameEn: 'Al Sakhabriya', nameAr: 'الصخبريه' },
  { zoneNumber: 73, nameEn: 'Al Samriya', nameAr: 'السمريه' },
  { zoneNumber: 73, nameEn: 'Al Samريه', nameAr: 'السمريه' },
  { zoneNumber: 73, nameEn: 'Al Sharayef', nameAr: 'الشرايف' },
  { zoneNumber: 73, nameEn: 'Al Shekaikat', nameAr: 'الشكيكات' },
  { zoneNumber: 73, nameEn: 'Al Suwaihliya', nameAr: 'السويحليه' },
  { zoneNumber: 73, nameEn: 'Bu Kharsaah', nameAr: 'بو خرسعه' },
  { zoneNumber: 73, nameEn: 'Bu Sidra', nameAr: 'بو سدره' },
  { zoneNumber: 73, nameEn: 'Bu Swayy', nameAr: 'بو اصوي' },
  { zoneNumber: 73, nameEn: 'Dohat Fashakh', nameAr: 'دوحة فشاخ' },
  { zoneNumber: 73, nameEn: 'Ebnaider Khoosa', nameAr: 'بنيدر خوصه' },
  { zoneNumber: 73, nameEn: 'Eghbatha', nameAr: 'اغباثة' },
  { zoneNumber: 73, nameEn: 'Getna', nameAr: 'قطنه' },
  { zoneNumber: 73, nameEn: 'Hazem Al Buhooth', nameAr: 'حزم البحوث' },
  { zoneNumber: 73, nameEn: 'Hazem Lejmiliya', nameAr: 'حزم لجمليه' },
  { zoneNumber: 73, nameEn: 'Ishlebdeen', nameAr: 'اشليبدين' },
  { zoneNumber: 73, nameEn: 'Jeleeb Fashakh', nameAr: 'جليب فشاخ' },
  { zoneNumber: 73, nameEn: 'Jery Al Hamra', nameAr: 'جري الحمره' },
  { zoneNumber: 73, nameEn: 'Jery Al Theeb', nameAr: 'جري الذيب' },
  { zoneNumber: 73, nameEn: 'Jery Bu Esh', nameAr: 'جري بو عش' },
  { zoneNumber: 73, nameEn: 'Jery Bu Ghanem', nameAr: 'جري بو غانم' },
  { zoneNumber: 73, nameEn: 'Jery Jafadeg', nameAr: 'جري جفادق' },
  { zoneNumber: 73, nameEn: 'Jery Letwar', nameAr: 'جري لطوار' },
  { zoneNumber: 73, nameEn: 'Jery Lubara', nameAr: 'جري لوبرة' },
  { zoneNumber: 73, nameEn: 'Jery Nazwa', nameAr: 'جري نزوه' },
  { zoneNumber: 73, nameEn: 'Jeryan Lijmiliya', nameAr: 'جريان لجمليه' },
  { zoneNumber: 73, nameEn: 'Khaznat Umm Al Zebad', nameAr: 'خزنة ام الزبد' },
  { zoneNumber: 73, nameEn: 'Lebsayyer', nameAr: 'لبصير' },
  { zoneNumber: 73, nameEn: 'Lijmiliya', nameAr: 'لجمليه' },
  { zoneNumber: 73, nameEn: 'Ras Umm Heesh', nameAr: 'راس ام حيش' },
  { zoneNumber: 73, nameEn: 'Rawadat Gharra', nameAr: 'روضة غره' },
  { zoneNumber: 73, nameEn: 'Rawdat Al Debdeba', nameAr: 'روضة الدبدبه' },
  { zoneNumber: 73, nameEn: 'Rawdat Al Hajla', nameAr: 'روضة الهجله' },
  { zoneNumber: 73, nameEn: 'Rawdat Al Jeraiba', nameAr: 'روضة الجريبه' },
  { zoneNumber: 73, nameEn: 'Rawdat Al Masluba', nameAr: 'روضة المصلبه' },
  { zoneNumber: 73, nameEn: 'Rawdat Al Mayya', nameAr: 'روضة الميه' },
  { zoneNumber: 73, nameEn: 'Rawdat Madhooy', nameAr: 'روضة مضحوي' },
  { zoneNumber: 73, nameEn: 'Rawdat Masab', nameAr: 'روضة مصعب' },
  { zoneNumber: 73, nameEn: 'Selaimi Al Bambara', nameAr: 'سليمي البمبره' },
  { zoneNumber: 73, nameEn: 'Umm Dahal', nameAr: 'ام دحل' },
  { zoneNumber: 73, nameEn: 'Umm Ghuwailina', nameAr: 'ام غويلينه' },
  { zoneNumber: 73, nameEn: 'Umm Heesh', nameAr: 'ام حيش' },
  { zoneNumber: 73, nameEn: 'Umm Sidra', nameAr: 'ام سدره' },
  { zoneNumber: 73, nameEn: 'Ummhat Heesh', nameAr: 'امهات حيش' },
  { zoneNumber: 73, nameEn: 'Waab Al Smaira', nameAr: 'وعب السميرة' },
  { zoneNumber: 73, nameEn: 'Wadi Al Buhooth', nameAr: 'وادي البحوث' },
  { zoneNumber: 73, nameEn: 'Wadi Fashakh', nameAr: 'وادي فشاخ' },
  { zoneNumber: 73, nameEn: 'Wadi Masab', nameAr: 'وادي مصعب' },
  { zoneNumber: 73, nameEn: 'Wadi Slema', nameAr: 'وادي اسلمة' },
  { zoneNumber: 74, nameEn: 'Al Egda', nameAr: 'العقدة' },
  { zoneNumber: 74, nameEn: 'Al Ghaleeda', nameAr: 'الغليظة' },
  { zoneNumber: 74, nameEn: 'Al Heedan', nameAr: 'الحيضان' },
  { zoneNumber: 74, nameEn: 'Al Jebail', nameAr: 'الجبيل' },
  { zoneNumber: 74, nameEn: 'Al Khor', nameAr: 'الخور' },
  { zoneNumber: 74, nameEn: 'Al Theebiya', nameAr: 'الذيبية' },
  { zoneNumber: 74, nameEn: 'Asat Al Raei', nameAr: 'عصاة الراعي' },
  { zoneNumber: 74, nameEn: 'Asma', nameAr: 'عصمة' },
  { zoneNumber: 74, nameEn: 'Bu Kheraisah', nameAr: 'بو خريسعة' },
  { zoneNumber: 74, nameEn: 'Heenat Al Meashab', nameAr: 'حينة المعشاب' },
  { zoneNumber: 74, nameEn: 'Industrial Area', nameAr: 'صناعية الخور' },
  { zoneNumber: 74, nameEn: 'Lemnaisbat', nameAr: 'لمنيصبات' },
  { zoneNumber: 74, nameEn: 'Mehairja', nameAr: 'محيرجة' },
  { zoneNumber: 74, nameEn: 'Muaither Rasheeda', nameAr: 'معيذر رشيدة' },
  { zoneNumber: 74, nameEn: 'Ras Al Gurma', nameAr: 'راس القرمة' },
  { zoneNumber: 74, nameEn: 'Ras Al Nekh', nameAr: 'راس النخ' },
  { zoneNumber: 74, nameEn: 'Ras Al Noof', nameAr: 'راس النوف' },
  { zoneNumber: 74, nameEn: 'Rasheeda', nameAr: 'رشيدة' },
  { zoneNumber: 74, nameEn: 'Rawdat Aras', nameAr: 'روضة عرص' },
  { zoneNumber: 74, nameEn: 'Rawdat Bakheela', nameAr: 'روضة بخيلة' },
  { zoneNumber: 74, nameEn: 'Rawdat Bu Fadala', nameAr: 'روضة بو فضالة' },
  { zoneNumber: 74, nameEn: 'Umm Al Hawaya', nameAr: 'ام الحوايا' },
  { zoneNumber: 74, nameEn: 'Umm Al Shukhoot', nameAr: 'ام الشخوط' },
  { zoneNumber: 74, nameEn: 'Umm Dahal', nameAr: 'ام دحل' },
  { zoneNumber: 74, nameEn: 'Umm Ejwaifa', nameAr: 'ام اجويفة' },
  { zoneNumber: 74, nameEn: 'Umm Enaig', nameAr: 'ام اعنيق' },
  { zoneNumber: 74, nameEn: 'Umm Ghuwailina', nameAr: 'ام غويلينة' },
  { zoneNumber: 74, nameEn: 'Umm Grain', nameAr: 'ام قرين' },
  { zoneNumber: 74, nameEn: 'Umm Smaira', nameAr: 'ام اسميرة' },
  { zoneNumber: 74, nameEn: 'Umm Swayya', nameAr: 'ام اسوية' },
  { zoneNumber: 74, nameEn: 'Wadi Al Banat', nameAr: 'وادي البنات' },
  { zoneNumber: 74, nameEn: 'Wadi Al Jalta', nameAr: 'وادي الجلتة' },
  { zoneNumber: 74, nameEn: 'Wadi Mehri', nameAr: 'وادي محري' },
  { zoneNumber: 75, nameEn: 'Abal Gararees', nameAr: 'ابا القراريص' },
  { zoneNumber: 75, nameEn: 'Al Ghesen', nameAr: 'الغصن' },
  { zoneNumber: 75, nameEn: 'Al Hashem', nameAr: 'الهشم' },
  { zoneNumber: 75, nameEn: 'Al Mamlaha', nameAr: 'المملحة' },
  { zoneNumber: 75, nameEn: 'Al Mashrab', nameAr: 'المشرب' },
  { zoneNumber: 75, nameEn: 'Al Thakhira', nameAr: 'الذخيرة' },
  { zoneNumber: 75, nameEn: 'Al Waab', nameAr: 'الوعب' },
  { zoneNumber: 75, nameEn: 'Birkat Rabiah', nameAr: 'بركة رابعة' },
  { zoneNumber: 75, nameEn: 'Bu Slaila', nameAr: 'بو صليلة' },
  { zoneNumber: 75, nameEn: 'Grayyat Al Faida', nameAr: 'اقريات الفايدة' },
  { zoneNumber: 75, nameEn: 'Imgaitna', nameAr: 'امقيطنة' },
  { zoneNumber: 75, nameEn: 'Khattaf', nameAr: 'خطاف' },
  { zoneNumber: 75, nameEn: 'Lebwairda', nameAr: 'لبويردة' },
  { zoneNumber: 75, nameEn: 'Lekhdaira', nameAr: 'لخضيرا' },
  { zoneNumber: 75, nameEn: 'Lekhrais', nameAr: 'لخريص' },
  { zoneNumber: 75, nameEn: 'Lemtaibnat', nameAr: 'لمتيبنات' },
  { zoneNumber: 75, nameEn: 'Madinat Al Kaaban', nameAr: 'مدينة الكعبان' },
  { zoneNumber: 75, nameEn: 'Ras Gertas', nameAr: 'راس قرطاس' },
  { zoneNumber: 75, nameEn: 'Ras Imlaiji', nameAr: 'راس امليجي' },
  { zoneNumber: 75, nameEn: 'Ras Mraidgha', nameAr: 'راس مريدغة' },
  { zoneNumber: 75, nameEn: 'Rass Laffan', nameAr: 'راس لفان' },
  { zoneNumber: 75, nameEn: 'Simsima', nameAr: 'سمسمة' },
  { zoneNumber: 75, nameEn: 'Umm Al Harabi', nameAr: 'ام الحرابي' },
  { zoneNumber: 75, nameEn: 'Umm Birka', nameAr: 'ام بركة' },
  { zoneNumber: 75, nameEn: 'Umm Ethnaitain', nameAr: 'ام اثنيتين' },
  { zoneNumber: 75, nameEn: 'Umm Graiba', nameAr: 'ام اقريبة' },
  { zoneNumber: 75, nameEn: 'Umm Theghaib', nameAr: 'ام ثغيب' },
  { zoneNumber: 75, nameEn: 'Waab Al Mashrab', nameAr: 'وعب المشرب' },
  { zoneNumber: 75, nameEn: 'Wadi Al Dehool', nameAr: 'وادي الدحول' },
  { zoneNumber: 75, nameEn: 'Wadi Al Gherban', nameAr: 'وادي الغربان' },
  { zoneNumber: 75, nameEn: 'Wadi Al Harm', nameAr: 'وادي الهرم' },
  { zoneNumber: 75, nameEn: 'Wadi Al Sahal', nameAr: 'وادي السهل' },
  { zoneNumber: 76, nameEn: 'Al Dawoodiya', nameAr: 'الداودية' },
  { zoneNumber: 76, nameEn: 'Al Deghaishiyat', nameAr: 'الدغيشيات' },
  { zoneNumber: 76, nameEn: 'Al Ghezlaniya', nameAr: 'الغزلانية' },
  { zoneNumber: 76, nameEn: 'Al Mayeda', nameAr: 'المايدة' },
  { zoneNumber: 76, nameEn: 'Al Mebtaeda', nameAr: 'المبتعدة' },
  { zoneNumber: 76, nameEn: 'Al Nefailiyat', nameAr: 'النفيليات' },
  { zoneNumber: 76, nameEn: 'Al Nehayy', nameAr: 'النهي' },
  { zoneNumber: 76, nameEn: 'Al Saalookiya', nameAr: 'الصعلوكية' },
  { zoneNumber: 76, nameEn: 'Al Selaimi', nameAr: 'السليمي' },
  { zoneNumber: 76, nameEn: 'Al Suwairiyat', nameAr: 'الصويريات' },
  { zoneNumber: 76, nameEn: 'Al Tabaah', nameAr: 'الطبعة' },
  { zoneNumber: 76, nameEn: 'Jery Al Theyab', nameAr: 'جري الذياب' },
  { zoneNumber: 76, nameEn: 'Leawaija', nameAr: 'لعويجا' },
  { zoneNumber: 76, nameEn: 'Leghraifa', nameAr: 'لغريفة' },
  { zoneNumber: 76, nameEn: 'Leghwair', nameAr: 'لغوير' },
  { zoneNumber: 76, nameEn: 'Leghwairiya', nameAr: 'لغويرية' },
  { zoneNumber: 76, nameEn: 'Lehnaizeeba', nameAr: 'لحنيزيبة' },
  { zoneNumber: 76, nameEn: 'Lesaiwed', nameAr: 'لسيود' },
  { zoneNumber: 76, nameEn: 'Rawdat Al Faras', nameAr: 'روضة الفرس' },
  { zoneNumber: 76, nameEn: 'Rawdat Hawtan', nameAr: 'روضة حوطان' },
  { zoneNumber: 76, nameEn: 'Umm Al Maa', nameAr: 'ام الماء' },
  { zoneNumber: 76, nameEn: 'Umm Graiba', nameAr: 'ام قريبة' },
  { zoneNumber: 76, nameEn: 'Umm Kheesa', nameAr: 'ام خيسة' },
  { zoneNumber: 76, nameEn: 'Umm Leadam', nameAr: 'ام لعظام' },
  { zoneNumber: 76, nameEn: 'Umm Leashoosh', nameAr: 'ام لعشوش' },
  { zoneNumber: 76, nameEn: 'Umm Lebrak', nameAr: 'ام لبرك' },
  { zoneNumber: 76, nameEn: 'Waab Labareg', nameAr: 'وعب لبارق' },
  { zoneNumber: 76, nameEn: 'Wadi Maitha', nameAr: 'وادي ميثا' },
  { zoneNumber: 76, nameEn: 'Yoodah', nameAr: 'يودة' },
  { zoneNumber: 77, nameEn: 'Abal Awsaj', nameAr: 'ابا العوسج' },
  { zoneNumber: 77, nameEn: 'Ain Snan', nameAr: 'عين سنان' },
  { zoneNumber: 77, nameEn: 'Al Ebb', nameAr: 'العب' },
  { zoneNumber: 77, nameEn: 'Al Ghashamiya', nameAr: 'الغشامية' },
  { zoneNumber: 77, nameEn: 'Al Hayer Al Gharbi', nameAr: 'الحاير الغربي' },
  { zoneNumber: 77, nameEn: 'Al Hayer Al Sharqi', nameAr: 'الحاير الشرقي' },
  { zoneNumber: 77, nameEn: 'Al Jassasiya', nameAr: 'الجساسية' },
  { zoneNumber: 77, nameEn: 'Al Mardiya', nameAr: 'الماردية' },
  { zoneNumber: 77, nameEn: 'Al Marroona', nameAr: 'المرونة' },
  { zoneNumber: 77, nameEn: 'Al Rekayy', nameAr: 'الركي' },
  { zoneNumber: 77, nameEn: 'Bu Bukhoora', nameAr: 'بو بخورة' },
  { zoneNumber: 77, nameEn: 'Bu Graita', nameAr: 'بو اقريطة' },
  { zoneNumber: 77, nameEn: 'Bu Shalloot', nameAr: 'بو شلوط' },
  { zoneNumber: 77, nameEn: 'Feleeha', nameAr: 'فليحة' },
  { zoneNumber: 77, nameEn: 'Fuwairit', nameAr: 'فويرط' },
  { zoneNumber: 77, nameEn: 'Imneefa', nameAr: 'امنيفة' },
  { zoneNumber: 77, nameEn: 'Lehwaila', nameAr: 'لحويلة' },
  { zoneNumber: 77, nameEn: 'Lejthaya', nameAr: 'لجذيع' },
  { zoneNumber: 77, nameEn: 'Rawdat Legreta', nameAr: 'روضة لقرطة' },
  { zoneNumber: 77, nameEn: 'Sebareet', nameAr: 'سباريت' },
  { zoneNumber: 77, nameEn: 'Sidriyat Al Kheesa', nameAr: 'سدرية الخيسة' },
  { zoneNumber: 77, nameEn: 'Umm Al Daah', nameAr: 'ام الضعة' },
  { zoneNumber: 77, nameEn: 'Umm Al Ghailam', nameAr: 'ام الغيلم' },
  { zoneNumber: 77, nameEn: 'Waab Al Kharab', nameAr: 'وعب الخراب' },
  { zoneNumber: 77, nameEn: 'Wadi Al Kheesa', nameAr: 'وادي الخيسة' },
  { zoneNumber: 77, nameEn: 'Wasit', nameAr: 'واسط' },
  { zoneNumber: 78, nameEn: 'Abwab', nameAr: 'ابواب' },
  { zoneNumber: 78, nameEn: 'Al Areesh', nameAr: 'العريش' },
  { zoneNumber: 78, nameEn: 'Al Zubara', nameAr: 'الزبارة' },
  { zoneNumber: 78, nameEn: 'Lejmail', nameAr: 'لجميل' },
  { zoneNumber: 78, nameEn: 'Lekhwair', nameAr: 'لخوير' },
  { zoneNumber: 78, nameEn: 'Ras Eshairij', nameAr: 'راس عشيرج' },
  { zoneNumber: 78, nameEn: 'Umm Jader', nameAr: 'ام جدر' },
  { zoneNumber: 79, nameEn: 'Al Khareeja', nameAr: 'الخريجة' },
  { zoneNumber: 79, nameEn: 'Al Mafyar', nameAr: 'المفير' },
  { zoneNumber: 79, nameEn: 'Al Nafla', nameAr: 'النافلة' },
  { zoneNumber: 79, nameEn: 'Al Shahniya', nameAr: 'الشاهنية' },
  { zoneNumber: 79, nameEn: 'Jabal Fuwairit', nameAr: 'جبل فويرط' },
  { zoneNumber: 79, nameEn: 'Jazeerat Reken', nameAr: 'جزيرة ركن' },
  { zoneNumber: 79, nameEn: 'Khasooma', nameAr: 'خاصومة' },
  { zoneNumber: 79, nameEn: 'Madinat Al Shamal', nameAr: 'مدينة الشمال' },
  { zoneNumber: 80, nameEn: 'Abal Jahazel', nameAr: 'ابا الجحازل' },
  { zoneNumber: 80, nameEn: 'Al Dehailiyat', nameAr: 'الدحيليات' },
  { zoneNumber: 80, nameEn: 'Al Mearad', nameAr: 'المعراض' },
  { zoneNumber: 80, nameEn: 'Al Negaib', nameAr: 'النقيب' },
  { zoneNumber: 80, nameEn: 'Al Ruwaidat', nameAr: 'الرويضات' },
  { zoneNumber: 80, nameEn: 'Al Samriya', nameAr: 'السمرية' },
  { zoneNumber: 80, nameEn: 'Al Sheehaniya', nameAr: 'الشيحانية' },
  { zoneNumber: 80, nameEn: 'Al Shekaikat', nameAr: 'الشكيكات' },
  { zoneNumber: 80, nameEn: 'Bu Ghawlana', nameAr: 'بو غولانة' },
  { zoneNumber: 80, nameEn: 'Jery Al Sahra', nameAr: 'جري الصحرا' },
  { zoneNumber: 80, nameEn: 'Jery Fatma', nameAr: 'جري فاطمة' },
  { zoneNumber: 80, nameEn: 'Lebsayyer', nameAr: 'لبصير' },
  { zoneNumber: 80, nameEn: 'Lebyatiya', nameAr: 'لبياتية' },
  { zoneNumber: 80, nameEn: 'Lehsiniya', nameAr: 'لحسنية' },
  { zoneNumber: 80, nameEn: 'Lekhraib', nameAr: 'لخريب' },
  { zoneNumber: 80, nameEn: 'Lubara', nameAr: 'لوبرة' },
  { zoneNumber: 80, nameEn: 'Umm Al Teen', nameAr: 'ام الطين' },
  { zoneNumber: 80, nameEn: 'Umm Dehail', nameAr: 'ام دحيل' },
  { zoneNumber: 80, nameEn: 'Umm Egdair', nameAr: 'ام اقدير' },
  { zoneNumber: 80, nameEn: 'Umm Enaig', nameAr: 'ام اعنيق' },
  { zoneNumber: 80, nameEn: 'Umm Leghab', nameAr: 'ام لقهاب' },
  { zoneNumber: 80, nameEn: 'Umm Legredi', nameAr: 'ام لقرضي' },
  { zoneNumber: 80, nameEn: 'Umm Lekhya', nameAr: 'ام لخيا' },
  { zoneNumber: 81, nameEn: 'Al Edaid Base', nameAr: 'قاعدة العديد' },
  { zoneNumber: 81, nameEn: 'Al Hemaila', nameAr: 'الحميلة' },
  { zoneNumber: 81, nameEn: 'Al Khaldiya', nameAr: 'الخالدية' },
  { zoneNumber: 81, nameEn: 'Bul Yuwabi', nameAr: 'بو اليوابي' },
  { zoneNumber: 81, nameEn: 'Jery Al Tuweela', nameAr: 'جري الطويلة' },
  { zoneNumber: 81, nameEn: 'Jeryan Al Reyoog', nameAr: 'جريان الريوق' },
  { zoneNumber: 81, nameEn: 'Mebaireek', nameAr: 'مبيريك' },
  { zoneNumber: 81, nameEn: 'Mekaines', nameAr: 'مكينس' },
  { zoneNumber: 81, nameEn: 'Small and Medium Industries Area', nameAr: 'منطقة الصناعات الصغيرة والمتوسطة' },
  { zoneNumber: 81, nameEn: 'Ummahat Owaina', nameAr: 'امهات عوينة' },
  { zoneNumber: 82, nameEn: 'Abal Erhayyat', nameAr: 'ابا الرحيات' },
  { zoneNumber: 82, nameEn: 'Abal Hasak', nameAr: 'ابا الحسك' },
  { zoneNumber: 82, nameEn: 'Al Ghesen', nameAr: 'الغصن' },
  { zoneNumber: 82, nameEn: 'Al Kharsaah', nameAr: 'الخرسعة' },
  { zoneNumber: 82, nameEn: 'Al Majmaah', nameAr: 'المجمعة' },
  { zoneNumber: 82, nameEn: 'Al Ruwayyed', nameAr: 'الرويض' },
  { zoneNumber: 82, nameEn: 'Al Sahla Al Shamaliya', nameAr: 'السهلة الشمالية' },
  { zoneNumber: 82, nameEn: 'Awjab Lejaada', nameAr: 'اوجاب لجعدة' },
  { zoneNumber: 82, nameEn: 'Beesha', nameAr: 'بيشة' },
  { zoneNumber: 82, nameEn: 'Bu Garn', nameAr: 'بو قرن' },
  { zoneNumber: 82, nameEn: 'Bu Silla', nameAr: 'بو صلة' },
  { zoneNumber: 82, nameEn: 'Iszhalat Al Markh', nameAr: 'اسهلة المرخ' },
  { zoneNumber: 82, nameEn: 'Jery Al Rasha', nameAr: 'جري الرشا' },
  { zoneNumber: 82, nameEn: 'Leabairi', nameAr: 'لعبيري' },
  { zoneNumber: 82, nameEn: 'Leawaija', nameAr: 'لعويجا' },
  { zoneNumber: 82, nameEn: 'Magareen Ibn Shuwaireb', nameAr: 'مقارين ابن شويرب' },
  { zoneNumber: 82, nameEn: 'Muaither Umm Al Zubar', nameAr: 'معيذر ام الزبار' },
  { zoneNumber: 82, nameEn: 'Rawdat Al Zamel', nameAr: 'روضة الزمل' },
  { zoneNumber: 82, nameEn: 'Rawdat Eshmaim', nameAr: 'روضة اشميم' },
  { zoneNumber: 82, nameEn: 'Rawdat Fadeel', nameAr: 'روضة فضيل' },
  { zoneNumber: 82, nameEn: 'Rawdat Kharja', nameAr: 'روضة خارجة' },
  { zoneNumber: 82, nameEn: 'Rawdat Rashed', nameAr: 'روضة راشد' },
  { zoneNumber: 82, nameEn: 'Umm Al Markh', nameAr: 'ام المرخ' },
  { zoneNumber: 82, nameEn: 'Umm Al Zubar East', nameAr: 'ام الزبار الشرقية' },
  { zoneNumber: 82, nameEn: 'Umm Al Zubar West', nameAr: 'ام الزبار الغربية' },
  { zoneNumber: 82, nameEn: 'Umm Ebairiya', nameAr: 'ام عبيرية' },
  { zoneNumber: 82, nameEn: 'Umm Garn', nameAr: 'ام قرن' },
  { zoneNumber: 82, nameEn: 'Umm Ghuwailina', nameAr: 'ام غويلينة' },
  { zoneNumber: 82, nameEn: 'Umm Harmala', nameAr: 'ام حرملة' },
  { zoneNumber: 82, nameEn: 'Umm Lebrak', nameAr: 'ام لبرك' },
  { zoneNumber: 82, nameEn: 'Umm Wishah', nameAr: 'ام وشاح' },
  { zoneNumber: 82, nameEn: 'Wadi Al Majhoola', nameAr: 'وادي المجهولة' },
  { zoneNumber: 82, nameEn: 'Wadi Al Sahala', nameAr: 'وادي السهلة' },
  { zoneNumber: 82, nameEn: 'Wadi Al Samriya', nameAr: 'وادي السمرية' },
  { zoneNumber: 82, nameEn: 'Wadi Lejmal Al Shamali', nameAr: 'وادي لجمال الشمالي' },
  { zoneNumber: 82, nameEn: 'Wadi Lejmal Sl Janoobi', nameAr: 'وادي لجمال الجنوبي' },
  { zoneNumber: 83, nameEn: 'Abal Hasak', nameAr: 'ابا الحسك' },
  { zoneNumber: 83, nameEn: 'Al Deainiyat', nameAr: 'الضعينيات' },
  { zoneNumber: 83, nameEn: 'Al Ghaf', nameAr: 'الغاف' },
  { zoneNumber: 83, nameEn: 'Al Jelaiat', nameAr: 'الجليعات' },
  { zoneNumber: 83, nameEn: 'Al Karaana', nameAr: 'الكرعانة' },
  { zoneNumber: 83, nameEn: 'Al Kharayej', nameAr: 'الخرايج' },
  { zoneNumber: 83, nameEn: 'Al Rekayya', nameAr: 'الركية' },
  { zoneNumber: 83, nameEn: 'Awjab Medhesh', nameAr: 'اوجاب مدهش' },
  { zoneNumber: 83, nameEn: 'Baida Al Gaa', nameAr: 'بيضا القاع' },
  { zoneNumber: 83, nameEn: 'Bu Daah', nameAr: 'بو ضعة' },
  { zoneNumber: 83, nameEn: 'Geezan Al Kharayej', nameAr: 'قيزان الخرايج' },
  { zoneNumber: 83, nameEn: 'Imshash Wadi Al Theyab', nameAr: 'مشاش وادي الذياب' },
  { zoneNumber: 83, nameEn: 'Jaww Al Nasla', nameAr: 'جو النصلة' },
  { zoneNumber: 83, nameEn: 'Jaww Basheer', nameAr: 'جو بشير' },
  { zoneNumber: 83, nameEn: 'Jeryan Al Butna', nameAr: 'جريان البطنة' },
  { zoneNumber: 83, nameEn: 'Leashara', nameAr: 'لعشرا' },
  { zoneNumber: 83, nameEn: 'Lebsaiteenat', nameAr: 'لبسيتينات' },
  { zoneNumber: 83, nameEn: 'Markhiyat Al Darb', nameAr: 'مرخية الدرب' },
  { zoneNumber: 83, nameEn: 'Rawdat Edghaim', nameAr: 'روضة ادغيم' },
  { zoneNumber: 83, nameEn: 'Sbaiha', nameAr: 'صبيحة' },
  { zoneNumber: 83, nameEn: 'Umm Ain', nameAr: 'ام عين' },
  { zoneNumber: 83, nameEn: 'Umm Al Jamajim', nameAr: 'ام الجماجم' },
  { zoneNumber: 83, nameEn: 'Umm Al Jefairat', nameAr: 'ام الجفيرات' },
  { zoneNumber: 83, nameEn: 'Umm Al Markh', nameAr: 'ام المرخ' },
  { zoneNumber: 83, nameEn: 'Umm Al Shubrum', nameAr: 'ام الشبرم' },
  { zoneNumber: 83, nameEn: 'Umm Al Suwab', nameAr: 'ام الصوب' },
  { zoneNumber: 83, nameEn: 'Umm Garn West', nameAr: 'ام قرن الغربية' },
  { zoneNumber: 83, nameEn: 'Ummahat Al Tuwwaim', nameAr: 'امهات التويم' },
  { zoneNumber: 83, nameEn: 'Wadi Al Markhiya', nameAr: 'وادي المرخية' },
  { zoneNumber: 83, nameEn: 'Wadi Lehwela', nameAr: 'وادي لهولة' },
  { zoneNumber: 84, nameEn: 'Al Hamla', nameAr: 'الهملة' },
  { zoneNumber: 84, nameEn: 'Al Shabhana', nameAr: 'الشبهانة' },
  { zoneNumber: 84, nameEn: 'Bu Ghawlana', nameAr: 'بو غولانة' },
  { zoneNumber: 84, nameEn: 'Bu Traifa', nameAr: 'بو اطريفة' },
  { zoneNumber: 84, nameEn: 'Ejbaijeb', nameAr: 'اجبيجب' },
  { zoneNumber: 84, nameEn: 'Jery Al Khanjar', nameAr: 'جري الخنجر' },
  { zoneNumber: 84, nameEn: 'Rawdat Al Arnab', nameAr: 'روضة الارنب' },
  { zoneNumber: 84, nameEn: 'Rawdat Al Barrag', nameAr: 'روضة البراق' },
  { zoneNumber: 84, nameEn: 'Rawdat Lebretha', nameAr: 'روضة لبرثة' },
  { zoneNumber: 84, nameEn: 'Umm Al Dayyat', nameAr: 'ام الضعيات' },
  { zoneNumber: 84, nameEn: 'Umm Al Suwwaid', nameAr: 'ام السويد' },
  { zoneNumber: 84, nameEn: 'Umm Bab', nameAr: 'ام باب' },
  { zoneNumber: 84, nameEn: 'Umm Samra', nameAr: 'ام سمرة' },
  { zoneNumber: 84, nameEn: 'Ummahat Anz', nameAr: 'امهات عنز' },
  { zoneNumber: 84, nameEn: 'Ummahat Slaim', nameAr: 'امهات اسليم' },
  { zoneNumber: 84, nameEn: 'Wadi Al Rashaida', nameAr: 'وادي الرشايدة' },
  { zoneNumber: 85, nameEn: 'Abal Asafeer', nameAr: 'ابا العصافير' },
  { zoneNumber: 85, nameEn: 'Abal Gararees', nameAr: 'ابا القراريص' },
  { zoneNumber: 85, nameEn: 'Abal Halayem', nameAr: 'ابا الهلايم' },
  { zoneNumber: 85, nameEn: 'Abal Hayyat', nameAr: 'ابا الحيات' },
  { zoneNumber: 85, nameEn: 'Abal Kharasa', nameAr: 'ابا الخراسع' },
  { zoneNumber: 85, nameEn: 'Al Hasheemiya', nameAr: 'الهشيمية' },
  { zoneNumber: 85, nameEn: 'Al Kharsaah', nameAr: 'الخرسعة' },
  { zoneNumber: 85, nameEn: 'Al Mehterga', nameAr: 'المحترقة' },
  { zoneNumber: 85, nameEn: 'Al Nasraniya', nameAr: 'النصرانية' },
  { zoneNumber: 85, nameEn: 'Al Nehaidain', nameAr: 'النهيدين' },
  { zoneNumber: 85, nameEn: 'Al Ruwaidat', nameAr: 'الرويضات' },
  { zoneNumber: 85, nameEn: 'Al Sehameya', nameAr: 'السحمية' },
  { zoneNumber: 85, nameEn: 'Al Semari', nameAr: 'السماري' },
  { zoneNumber: 85, nameEn: 'Al Shedeeda', nameAr: 'الشديدة' },
  { zoneNumber: 85, nameEn: 'Al Shelaibdeenat', nameAr: 'الشليبدينات' },
  { zoneNumber: 85, nameEn: 'Al Sidri', nameAr: 'السدري' },
  { zoneNumber: 85, nameEn: 'Al Slemiya', nameAr: 'السلمية' },
  { zoneNumber: 85, nameEn: 'Al Thumama', nameAr: 'الثمامة' },
  { zoneNumber: 85, nameEn: 'Awjab Al Sabur', nameAr: 'اوجاب السبر' },
  { zoneNumber: 85, nameEn: 'Bu Braika', nameAr: 'بو بريكة' },
  { zoneNumber: 85, nameEn: 'Bu Ghameela', nameAr: 'بو غميلة' },
  { zoneNumber: 85, nameEn: 'Esaila', nameAr: 'عسيلة' },
  { zoneNumber: 85, nameEn: 'Hazem Bu Awseja', nameAr: 'حزم بو عوسجة' },
  { zoneNumber: 85, nameEn: 'Imlaih', nameAr: 'امليح' },
  { zoneNumber: 85, nameEn: 'Jarr Khaleel', nameAr: 'جر خليل' },
  { zoneNumber: 85, nameEn: 'Jarr Leadam', nameAr: 'جر لعظام' },
  { zoneNumber: 85, nameEn: 'Jaww Al Ekresh', nameAr: 'جو العكرش' },
  { zoneNumber: 85, nameEn: 'Jery Aba Slailat', nameAr: 'جري ابا صليلات' },
  { zoneNumber: 85, nameEn: 'Jery Tawg', nameAr: 'جري طوق' },
  { zoneNumber: 85, nameEn: 'Jeryan Al Saiha', nameAr: 'جريان الصيحة' },
  { zoneNumber: 85, nameEn: 'Labhariya', nameAr: 'لبهرية' },
  { zoneNumber: 85, nameEn: 'Leawaina', nameAr: 'لعوينة' },
  { zoneNumber: 85, nameEn: 'Lebrega', nameAr: 'لبرقة' },
  { zoneNumber: 85, nameEn: 'Lejhaimiya', nameAr: 'لجهيمية' },
  { zoneNumber: 85, nameEn: 'Ludaihiya', nameAr: 'لوضيحية' },
  { zoneNumber: 85, nameEn: 'Muaither Sidran', nameAr: 'معيذر سدران' },
  { zoneNumber: 85, nameEn: 'Rawdat Al Nefafees', nameAr: 'روضة النفافيس' },
  { zoneNumber: 85, nameEn: 'Rawdat Mraighan', nameAr: 'روضة مريغان' },
  { zoneNumber: 85, nameEn: 'Semari Jery Tawg', nameAr: 'سماري جري طوق' },
  { zoneNumber: 85, nameEn: 'Snay Shagra', nameAr: 'صنيع شقرا' },
  { zoneNumber: 85, nameEn: 'Tharb', nameAr: 'ذرب' },
  { zoneNumber: 85, nameEn: 'Thenyet Al Jamal', nameAr: 'ثنية الجمل' },
  { zoneNumber: 85, nameEn: 'Umm Al Gararees', nameAr: 'ام القراريص' },
  { zoneNumber: 85, nameEn: 'Umm Garn', nameAr: 'ام قرن' },
  { zoneNumber: 85, nameEn: 'Umm Taga', nameAr: 'ام طاقة' },
  { zoneNumber: 85, nameEn: 'Umm Thumam', nameAr: 'ام ثمام' },
  { zoneNumber: 85, nameEn: 'Ummahat Slal', nameAr: 'امهات صلال' },
  { zoneNumber: 85, nameEn: 'Ummahat Swayy', nameAr: 'امهات اصوي' },
  { zoneNumber: 85, nameEn: 'Wadi Al Ekresh', nameAr: 'وادي العكرش' },
  { zoneNumber: 85, nameEn: 'Wadi Al Markh', nameAr: 'وادي المرخ' },
  { zoneNumber: 85, nameEn: 'Wadi Lemghadar', nameAr: 'وادي لمغدر' },
  { zoneNumber: 85, nameEn: 'Wadi Umm Al Theyab', nameAr: 'وادي ام الذياب' },
  { zoneNumber: 85, nameEn: 'Wadi Umm Al Zubar', nameAr: 'وادي ام الزبار' },
  { zoneNumber: 86, nameEn: 'Afjan', nameAr: 'عفجان' },
  { zoneNumber: 86, nameEn: 'Al Ruwais West', nameAr: 'الرويس الغربية' },
  { zoneNumber: 86, nameEn: 'Al Zeghain', nameAr: 'الزغين' },
  { zoneNumber: 86, nameEn: 'Barga Egaif', nameAr: 'برقا اعقيف' },
  { zoneNumber: 86, nameEn: 'Dukhan', nameAr: 'دخان' },
  { zoneNumber: 86, nameEn: 'Fehaiheel', nameAr: 'فحيحيل' },
  { zoneNumber: 86, nameEn: 'Jaww Al Bab', nameAr: 'جو الباب' },
  { zoneNumber: 86, nameEn: 'Jaww Al Banat', nameAr: 'جو البنات' },
  { zoneNumber: 86, nameEn: 'Jaww Esrayya', nameAr: 'جو اسريع' },
  { zoneNumber: 86, nameEn: 'New Al Khattiya', nameAr: 'الخطية الجديدة' },
  { zoneNumber: 86, nameEn: 'Ras Al Ghariya', nameAr: 'راس الغارية' },
  { zoneNumber: 86, nameEn: 'Ras Dukhan', nameAr: 'راس دخان' },
  { zoneNumber: 86, nameEn: 'Rawdat Jarrah', nameAr: 'روضة جراح' },
  { zoneNumber: 86, nameEn: 'Umm Wadi', nameAr: 'ام وادي' },
  { zoneNumber: 86, nameEn: 'Wadi Imhalat', nameAr: 'وادي امهلط' },
  { zoneNumber: 90, nameEn: 'Al Wakra', nameAr: 'الوكرة' },
  { zoneNumber: 90, nameEn: 'Al Wakra - Industrial Area - الوكرة', nameAr: 'المنطقة الصناعية' },
  { zoneNumber: 90, nameEn: 'Al Wakra South East', nameAr: 'الوكرة جنوب شرق' },
  { zoneNumber: 91, nameEn: 'Afjat Muaither', nameAr: 'عفجة معيذر' },
  { zoneNumber: 91, nameEn: 'Al Meshaf', nameAr: 'المشاف' },
  { zoneNumber: 91, nameEn: 'Al Nebah', nameAr: 'النباه' },
  { zoneNumber: 91, nameEn: 'Al Rakb', nameAr: 'الركب' },
  { zoneNumber: 91, nameEn: 'Al Wukair', nameAr: 'الوكير' },
  { zoneNumber: 91, nameEn: 'Birkat Al Awamer', nameAr: 'بركة العوامر' },
  { zoneNumber: 91, nameEn: 'Bu Sulba', nameAr: 'بو صلبة' },
  { zoneNumber: 91, nameEn: 'Bul Hemmaid', nameAr: 'بو الحميض' },
  { zoneNumber: 91, nameEn: 'Jery Musabbeh', nameAr: 'جري مصبح' },
  { zoneNumber: 91, nameEn: 'Muaither Al Wukair', nameAr: 'معيذر الوكير' },
  { zoneNumber: 91, nameEn: 'Umm Besher', nameAr: 'ام بشر' },
  { zoneNumber: 91, nameEn: 'Wadi Aba Seleel', nameAr: 'وادي ابا الصليل' },
  { zoneNumber: 92, nameEn: 'Al Rakb', nameAr: 'الركب' },
  { zoneNumber: 92, nameEn: 'Mesaieed', nameAr: 'مسيعيد' },
  { zoneNumber: 92, nameEn: 'Mesaieed - Free Zone - مسيعيد', nameAr: 'المنطقة الحرة' },
  { zoneNumber: 93, nameEn: 'Mesaieed', nameAr: 'مسيعيد' },
  { zoneNumber: 93, nameEn: 'Negyan Mesaieed', nameAr: 'نقيان مسيعيد' },
  { zoneNumber: 93, nameEn: 'Sealine', nameAr: 'سيلين' },
  { zoneNumber: 94, nameEn: 'Afjat Saadoon', nameAr: 'عفجة سعدون' },
  { zoneNumber: 94, nameEn: 'Al Afja', nameAr: 'العفجة' },
  { zoneNumber: 94, nameEn: 'Al Markhiya South', nameAr: 'المرخية الجنوبية' },
  { zoneNumber: 94, nameEn: 'Al Metfardat', nameAr: 'المتفردات' },
  { zoneNumber: 94, nameEn: 'Eghbai Al Daww', nameAr: 'اغبي الضو' },
  { zoneNumber: 94, nameEn: 'Jabal Marmi', nameAr: 'جبل مرمي' },
  { zoneNumber: 94, nameEn: 'Khuwaiteem', nameAr: 'خويتيم' },
  { zoneNumber: 94, nameEn: 'Leshaiger', nameAr: 'لشيقر' },
  { zoneNumber: 94, nameEn: 'Lezaireg', nameAr: 'لزيرق' },
  { zoneNumber: 94, nameEn: 'Nega Al Fagara', nameAr: 'نقا الفقارة' },
  { zoneNumber: 94, nameEn: 'Nega Al Mamlaha', nameAr: 'نقا المملحة' },
  { zoneNumber: 94, nameEn: 'Nega Al Sahla', nameAr: 'نقا السهلة' },
  { zoneNumber: 94, nameEn: 'Nega Attiya', nameAr: 'نقا عطية' },
  { zoneNumber: 94, nameEn: 'Nega Umm Slema', nameAr: 'نقا ام اسلمة' },
  { zoneNumber: 94, nameEn: 'Shagra', nameAr: 'شقرا' },
  { zoneNumber: 94, nameEn: 'Zarga', nameAr: 'زرقا' },
  { zoneNumber: 95, nameEn: 'Al Baoodiyat', nameAr: 'البعوضيات' },
  { zoneNumber: 95, nameEn: 'Al Daiha', nameAr: 'الديحة' },
  { zoneNumber: 95, nameEn: 'Al Fasl', nameAr: 'الفصل' },
  { zoneNumber: 95, nameEn: 'Al Kharrara', nameAr: 'الخرارة' },
  { zoneNumber: 95, nameEn: 'Al Mefeed', nameAr: 'المفيض' },
  { zoneNumber: 95, nameEn: 'Al Nehaidain', nameAr: 'النهيدين' },
  { zoneNumber: 95, nameEn: 'Al Nigyan', nameAr: 'النقيان' },
  { zoneNumber: 95, nameEn: 'Al Sidari', nameAr: 'السداري' },
  { zoneNumber: 95, nameEn: 'Awjab Lekhlas', nameAr: 'اوجاب لخلاص' },
  { zoneNumber: 95, nameEn: 'Bu Jood', nameAr: 'بو جود' },
  { zoneNumber: 95, nameEn: 'Ghasham', nameAr: 'غشام' },
  { zoneNumber: 95, nameEn: 'Hasheemiyat Al Kharrara', nameAr: 'هشيمية الخرارة' },
  { zoneNumber: 95, nameEn: 'Lejkhainiya', nameAr: 'لجخينية' },
  { zoneNumber: 95, nameEn: 'Lekhbaib', nameAr: 'لخبيب' },
  { zoneNumber: 95, nameEn: 'Mesaigra', nameAr: 'مصيقرة' },
  { zoneNumber: 95, nameEn: 'Nega Bu Birka', nameAr: 'نقا بو بركة' },
  { zoneNumber: 95, nameEn: 'Nega Bu Dulooa', nameAr: 'نقا بو ضلوع' },
  { zoneNumber: 95, nameEn: 'Nega Bu Gutbetain', nameAr: 'نقا بو قطبتين' },
  { zoneNumber: 95, nameEn: 'Nega Bu Hajla', nameAr: 'نقا بو هجلة' },
  { zoneNumber: 95, nameEn: 'Nega Bu Sajat', nameAr: 'نقا بو صاجات' },
  { zoneNumber: 95, nameEn: 'Nega Nayef', nameAr: 'نقا نايف' },
  { zoneNumber: 95, nameEn: 'Sand Plant', nameAr: 'مصنع الرمل' },
  { zoneNumber: 95, nameEn: 'Swaidat Al Warag', nameAr: 'سويدات الورق' },
  { zoneNumber: 95, nameEn: 'Traina', nameAr: 'ترينة' },
  { zoneNumber: 95, nameEn: 'Umm Al Rumram', nameAr: 'ام الرمرام' },
  { zoneNumber: 95, nameEn: 'Umm Garn', nameAr: 'ام قرن' },
  { zoneNumber: 95, nameEn: 'Umm Jawlag', nameAr: 'ام جولق' },
  { zoneNumber: 95, nameEn: 'Ummat Maghati', nameAr: 'امات مغاطي' },
  { zoneNumber: 95, nameEn: 'Wadi Jallal', nameAr: 'وادي جلال' },
  { zoneNumber: 96, nameEn: 'Ain Hamad', nameAr: 'عين حمد' },
  { zoneNumber: 96, nameEn: 'Al Aamriya', nameAr: 'العامرية' },
  { zoneNumber: 96, nameEn: 'Al Galayel', nameAr: 'القلايل' },
  { zoneNumber: 96, nameEn: 'Al Kharaitiyat West', nameAr: 'الخريطيات الغربية' },
  { zoneNumber: 96, nameEn: 'Al Maszhabiya', nameAr: 'المسحبية' },
  { zoneNumber: 96, nameEn: 'Al Sabsab', nameAr: 'السبسب' },
  { zoneNumber: 96, nameEn: 'Al Slemiya', nameAr: 'السلمية' },
  { zoneNumber: 96, nameEn: 'Al Snaiat', nameAr: 'الصنيعات' },
  { zoneNumber: 96, nameEn: 'Awhalat Al Karayej', nameAr: 'اوحلة الخرايج' },
  { zoneNumber: 96, nameEn: 'Barga Haleema', nameAr: 'برقا حليمة' },
  { zoneNumber: 96, nameEn: 'Bu Samra', nameAr: 'بو سمرة' },
  { zoneNumber: 96, nameEn: 'Dohat Salwa', nameAr: 'دوحة سلوى' },
  { zoneNumber: 96, nameEn: 'Eglat Faisal', nameAr: 'عقلة فيصل' },
  { zoneNumber: 96, nameEn: 'Hazm Abal Jihh', nameAr: 'حزم ابا الجح' },
  { zoneNumber: 96, nameEn: 'Imshash Bin Shafi', nameAr: 'امشاش بن شافي' },
  { zoneNumber: 96, nameEn: 'Imshash Lekhwan', nameAr: 'امشاش لخوان' },
  { zoneNumber: 96, nameEn: 'Jaww Bu Eshjara', nameAr: 'جو بو اشجرة' },
  { zoneNumber: 96, nameEn: 'Jelaiat Ali Bin Saeed', nameAr: 'جليعات علي بن سعيد' },
  { zoneNumber: 96, nameEn: 'Khashem Al Nekhsh', nameAr: 'خشم النخش' },
  { zoneNumber: 96, nameEn: 'Learaig', nameAr: 'لعريق' },
  { zoneNumber: 96, nameEn: 'Lemshash', nameAr: 'لمشاش' },
  { zoneNumber: 96, nameEn: 'Lusail West', nameAr: 'لوسيل الغربية' },
  { zoneNumber: 96, nameEn: 'Nega Umm Garn', nameAr: 'نقا ام قرن' },
  { zoneNumber: 96, nameEn: 'Rawdat Al Markh', nameAr: 'روضة المرخ' },
  { zoneNumber: 96, nameEn: 'Rawdat Ekdaim', nameAr: 'روضة اكظيم' },
  { zoneNumber: 96, nameEn: 'Rawdat Humra', nameAr: 'روضة حمرة' },
  { zoneNumber: 96, nameEn: 'Rawdat Ishala', nameAr: 'روضة اشعلا' },
  { zoneNumber: 96, nameEn: 'Rawdat Umm Samra', nameAr: 'روضة ام سمرة' },
  { zoneNumber: 96, nameEn: 'Reyad Al Markh', nameAr: 'رياض المرخ' },
  { zoneNumber: 96, nameEn: 'Tuwar Lehraithi', nameAr: 'طوار لحريثي' },
  { zoneNumber: 96, nameEn: 'Umm Ain', nameAr: 'ام عين' },
  { zoneNumber: 96, nameEn: 'Umm Al Jaratheem', nameAr: 'ام الجراثيم' },
  { zoneNumber: 96, nameEn: 'Umm Al Masam', nameAr: 'ام المسام' },
  { zoneNumber: 96, nameEn: 'Umm Al Tuwaim', nameAr: 'ام التويم' },
  { zoneNumber: 96, nameEn: 'Umm Hawta', nameAr: 'ام حوطة' },
  { zoneNumber: 96, nameEn: 'Umm Jarra', nameAr: 'ام جرة' },
  { zoneNumber: 96, nameEn: 'Ummahat Al Markh', nameAr: 'امهات المرخ' },
  { zoneNumber: 96, nameEn: 'Wadi Al Jihh', nameAr: 'وادي الجح' },
  { zoneNumber: 96, nameEn: 'Wadi Lekhwan', nameAr: 'وادي لخوان' },
  { zoneNumber: 97, nameEn: 'Al Garayen', nameAr: 'القراين' },
  { zoneNumber: 97, nameEn: 'Barga Al Hamil', nameAr: 'برقا الهامل' },
  { zoneNumber: 97, nameEn: 'Barga Al Kharaz', nameAr: 'برقا الخراز' },
  { zoneNumber: 97, nameEn: 'Geezan Learaig', nameAr: 'قيزان لعريق' },
  { zoneNumber: 97, nameEn: 'Ghareb Al Thawr', nameAr: 'غارب الثور' },
  { zoneNumber: 97, nameEn: 'Jaww Al Banat', nameAr: 'جو البنات' },
  { zoneNumber: 97, nameEn: 'Jaww Al Kharaz', nameAr: 'جو الخراز' },
  { zoneNumber: 97, nameEn: 'Jaww Al Salama', nameAr: 'جو السلامة' },
  { zoneNumber: 97, nameEn: 'Nega Al Harja', nameAr: 'نقا الحرجة' },
  { zoneNumber: 97, nameEn: 'Rawdat Al Faras', nameAr: 'روضة الفرس' },
  { zoneNumber: 97, nameEn: 'Sawda Natheel', nameAr: 'سودا نثيل' },
  { zoneNumber: 97, nameEn: 'Zubarat Learaig', nameAr: 'زبارة لعريق' },
  { zoneNumber: 98, nameEn: 'Aamra', nameAr: 'عامرة' },
  { zoneNumber: 98, nameEn: 'Al Mamlaha', nameAr: 'المملحة' },
  { zoneNumber: 98, nameEn: 'Bu Traifa', nameAr: 'بو اطريفة' },
  { zoneNumber: 98, nameEn: 'Eglat Al Manaseer', nameAr: 'عقلة المناصير' },
  { zoneNumber: 98, nameEn: 'Eglat Zuwayyed', nameAr: 'عقلة زويد' },
  { zoneNumber: 98, nameEn: 'Jaww Lekhreza', nameAr: 'جو لخرزة' },
  { zoneNumber: 98, nameEn: 'Khor Leadaid', nameAr: 'خور لعديد' },
  { zoneNumber: 98, nameEn: 'Legsaira', nameAr: 'لقصيرة' },
  { zoneNumber: 98, nameEn: 'Lekbooa', nameAr: 'لكبوع' },
  { zoneNumber: 98, nameEn: 'Lekhfoos', nameAr: 'لخفوس' },
  { zoneNumber: 98, nameEn: 'Nega Al Daiha', nameAr: 'نقا الديحة' },
  { zoneNumber: 98, nameEn: 'Nega Al Fagara', nameAr: 'نقا الفقارة' },
  { zoneNumber: 98, nameEn: 'Negyan Al Radda', nameAr: 'نقيان الردة' },
  { zoneNumber: 98, nameEn: 'Negyan Al Sada', nameAr: 'نقيان السادة' },
  { zoneNumber: 98, nameEn: 'Ras Al Maharef', nameAr: 'راس المحارف' },
  { zoneNumber: 98, nameEn: 'Wadi Abal Gherban', nameAr: 'وادي ابا الغربان' },
];

// Every named area, sorted by English name -- covers all 98 numbered zones plus areas
// with no official zone number (zoneNumber 0), so there's no need to make the customer
// pick a municipality first before narrowing it down; one search-friendly select is enough.
export const qatarAreasSorted: QatarArea[] = [...qatarAreas].sort((a, b) => a.nameEn.localeCompare(b.nameEn));
